### ISSUE TITLE
Names for rules show as "Unknown"

### ISSUE THREAD

**Issue by gewarren** [dotnet/roslyn-analyzers#2473]
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v2.9.2

#### Repro steps

1. Create a new C# .NET Core console app in VS 2019.
1. Drag and drop the MaintainabilityRulesEnabled.ruleset file from C:\Users\you\.nuget\packages\microsoft.codeanalysis.fxcopanalyzers\2.9.2\rulesets to Solution Explorer. The rule set opens in the editor.
1. Expand the Microsoft.CodeQuality.CSharp.Analyzers and Microsoft.CodeQuality.VisualBasic.Analyzers nodes.

#### Expected behavior

Names display in Name column.

#### Actual behavior

Name column shows "Unknown" for all the rules.

![image](https://user-images.githubusercontent.com/24882762/57946055-42a14600-7890-11e9-876e-4ea44c02c033.png)

**Comment by Gav-Brown** [comment]
Applies to any analyser e.g. StyleCop, ErrorProne.Structs etc.
Applies to Visual Studio 2017 and 2019.
Only the old `Managed Binary Analysis` and `Microsoft.Analyzers.NativeCodeAnalysis` show the names.

**Comment by Gav-Brown** [comment]
Reported previously at DotNetAnalyzers/StyleCopAnalyzers#2340 but never fully resolved.

**Comment by Gav-Brown** [comment]
As an aside, now the Visual Studio ruleset editor no longer shows new rules eg. update to latest [FXCop analysers v2.9.3](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers) and all the new rules do not show in the editor, so you can't enable or disable them.

**Comment by mavasani** [comment]
The issue here was not related to analyzer package, but a bug in ruleset editor. This has been fixed in VS2019 16.3

**Comment by mavasani** [comment]
![image](https://user-images.githubusercontent.com/10605811/63552499-9c975480-c4ec-11e9-8e64-6df73c7cd3b9.png)

**Comment by richard-ob** [comment]
@mavasani Still seeing this exact issue in 16.2.4. Rules from StyleCop.Analyzers just show "Unknown" as the name via the Ruleset editor.

**Comment by Gav-Brown** [comment]
@richard-ob I believe @mavasani mentioned this is fix in `16.3`, see https://github.com/dotnet/roslyn-analyzers/issues/2473#issuecomment-524092231 above

**Comment by richard-ob** [comment]
@Gav-Brown Apologies, I'd read the post wrong. I'd wrongly assumed that 16.3 was released, and thus having the latest publicly available version had the fix in it. Will keep my eyes peeled for the new version.

**Comment by MoonStorm** [comment]
This issue is still not fixed. Using version 16.3.8, I copied the rule set _AllRulesEnabled.ruleset_ from _.nuget\packages\microsoft.codeanalysis.fxcopanalyzers\2.9.7\rulesets_  in my solution folder and I get the following screen in the ruleset editor:
![Unknown](https://user-images.githubusercontent.com/2178827/68252461-d8699280-ffe2-11e9-8e18-379642596c1f.PNG)
