### ISSUE TITLE
Suppress button disabled for CA1801 

### ISSUE THREAD

**Issue by bidolah** [dotnet/roslyn-analyzers#3579]
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v2.9.8 - v3.0.0
(not checked on previous versions)

#### Diagnostic ID

[CA1801 ](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1801?view=vs-2019)

#### VS Version

2019 Pro (latest)

#### Repro steps

1. Add methods with unused parameter
2. Change severity for CA1801 to Error
3. Build project to see the warning in the error list
4. Right-click and select "Suppress" in the context menu
[Example](https://github.com/bidolah/codeAnalysisBug)

![image](https://user-images.githubusercontent.com/9832538/80624209-07be0100-8a54-11ea-8ca9-4677709e6fcd.png)

#### Actual behavior Button is disabled

Looks like Visual Studio run legacy code analysis tool because the error displayed only after the build and not displayed after open cs file (live analysis enabled):
![image](https://user-images.githubusercontent.com/9832538/80624126-e826d880-8a53-11ea-93b4-a7e1098873ab.png)

1) Why I can't suppress it with context menu?
2) Why error not displayed immediately after write code, not after build
3) Same behavior reproduced for other rules with the "Compiler" tool?

**Comment by mavasani** [comment]
This should be fixed with analyzer package 3.0.0. Also note that when attempting the scenario for first time after starting VS, you may have to wait for couple of seconds before the context menu shows up.

![image](https://user-images.githubusercontent.com/10605811/80629512-cc95e080-8a07-11ea-91d1-702be7fb2653.png)

**Comment by bidolah** [comment]
Error still reproduced with 3.0.0
![image](https://user-images.githubusercontent.com/9832538/80632019-4c9b6500-8a5f-11ea-80dd-a42278c65e9d.png)

**Comment by bidolah** [comment]
Maybe you need more details? I can send you more detailed steps if you want

**Comment by mavasani** [comment]
@bidolah Yes, please provide more details. Note that diagnostics that come directly from build do not have option to be suppressed as they might be stale. Only intellisense diagnostics can be suppressed, which should up when you double click the error and the source file with that entry opens up. Make sure that the "Suppression State" column for the entry shows "Active". See details here: https://github.com/dotnet/roslyn/issues/11371

**Comment by bidolah** [comment]
@mavasani It looks like it's coming from Build diagnostics, but I don't understand why.
CA1801 ported to the new Microsoft.CodeAnalysis.FxCopAnalyzers, it means that rules should use IntelliSense diagnostics (tools work directly with source code syntax, not with Intermediate Language)?  I see the difference with your screenshot and my, "Tool" column is different "Compiler" and "Microsoft.CodeQuality.Analyzer" but legacy code rules were disabled in my example (<RunCodeAnalysis>false<RunCodeAnalysis> inside .csproj) and Microsoft.CodeAnalysis.FxCopAnalyzers package added to the project. I expect that when I open the file with error CA1801 it will be immediately seen in Error List, but it's not happening, I must build project to see the error.

**Comment by mavasani** [comment]
@bidolah Can you make sure you use version 3.0.0 of FxCopAnalyzers package? In earlier versions, CA1801 was a build only diagnostic.

**Comment by Evangelink** [comment]
@bidolah Are you still experiencing the same issue with the v3.0.0 of the analyzer?

**Comment by Evangelink** [comment]
Ping @bidolah

**Comment by Evangelink** [comment]
Feel free to reopen if you still experience the issue @bidolah
