### ISSUE TITLE
CompareSymbolsCorrectlyAnalyzer threw an exception of type NullReferenceException

### ISSUE THREAD

**Issue by KrisVandermotten** [dotnet/roslyn-analyzers#4414]
Consider the following code:

```cs
var d = new Dictionary<IMethodSymbol, (int position, IMethodSymbol[] references)>(SymbolEqualityComparer.Default);
```

Compiling this results in:

```
Analyzer 'Microsoft.CodeAnalysis.Analyzers.MetaAnalyzers.CompareSymbolsCorrectlyAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'De objectverwijzing is niet op een exemplaar van een object ingesteld.'.
Exception occurred with following context:
Compilation: [...]
IOperation: ObjectCreation
SyntaxTree: [...]
SyntaxNode: [...]

System.NullReferenceException: De objectverwijzing is niet op een exemplaar van een object ingesteld.
   at Microsoft.CodeAnalysis.Analyzers.MetaAnalyzers.CompareSymbolsCorrectlyAnalyzer.<>c__DisplayClass15_0.<HandleObjectCreation>b__0(IArgumentOperation arg)
   at System.Linq.ImmutableArrayExtensions.Any[T](ImmutableArray`1 immutableArray, Func`2 predicate)
   at Microsoft.CodeAnalysis.Analyzers.MetaAnalyzers.CompareSymbolsCorrectlyAnalyzer.HandleObjectCreation(OperationAnalysisContext& context, INamedTypeSymbol symbolType, INamedTypeSymbol symbolEqualityComparerType, ImmutableHashSet`1 collectionTypes)
   at Microsoft.CodeAnalysis.Analyzers.MetaAnalyzers.CompareSymbolsCorrectlyAnalyzer.<>c__DisplayClass12_1.<Initialize>b__3(OperationAnalysisContext context)
```

**Comment by michsco** [comment]
Seeing the exact same error.

**Comment by JasonBock** [comment]
Seeing the same with `HashSet<ITypeSymbol>`. The only way to get around this is to suppress the issue in code for now. :(

**Comment by Evangelink** [comment]
Seems to relate to #4470 and #4568, issues have been fixed and I have just tested on master, there is no longer any issue.

I am closing the issue, if you are still affected, could you please ping us and ideally provide some reproducer and the version of the analyzer you are using?!

**Comment by Sergio0694** [comment]
I'm still seeing this error in VS 16.9 Preview 4 (just updated to it) 🤔
Should that be tracked here (possibly reopening the issue), or should I open another issue for that?

Here's what I'm seeing when compiling my source generator:

![image](https://user-images.githubusercontent.com/10199417/107428402-ddd95500-6b22-11eb-89f1-7ee5916abc6e.png)

I also have repro steps if that helps:
- Clone https://github.com/Sergio0694/ComputeSharp
- Checkout to `dev`
- Build the `ComputeSharp.SourceGenerators` project in VS
**OR**
- Build the `ComputeSharp.Package` .msproj project from with `dotnet build`

**Comment by Evangelink** [comment]
@Sergio0694 I am doing the VS update now and will let you know if I find somehting.

**Comment by Evangelink** [comment]
Got a restore error: The local source 'C:\Src\ComputeSharp\src\ComputeSharp.Package\bin\Release' doesn't exist.

**Comment by Sergio0694** [comment]
@Evangelink Thank you for your time and for taking a look, I appreciate it! 😄

**Comment by Evangelink** [comment]
@Sergio0694 I stop having the issue as soon as I bump the version of `Microsoft.CodeAnalysis.Analyzers` from `3.3.1` to `3.3.2`, do a clean and rebuild. Could you confirm that's also solving the issue on your side?

**Comment by Sergio0694** [comment]
@Evangelink I can confirm that upgrading to `3.3.2` does fix those exceptions, awesome!
Sorry for having pinged you all in here then, glad there was such an easy fix that I had just missed though! 😄
Thanks again for your time!
