### ISSUE TITLE
CA2254 Should not apply when log message template references constant values

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/roslyn-analyzers#5415]
The following code block receives info messages from CA2254 despite the interpolated values (the `nameof()` expression) being constant:
``` c#
private static IParameterBinder<TModel> LookupBinder(IServiceProvider services, ILogger logger)
{
    var binder = services.GetService<IParameterBinder<TModel>>();

    if (binder is not null)
    {
        logger.LogDebug($"{nameof(IParameterBinder<object>)}<{{0}}> resolved from DI container.", typeof(TModel).Name);

        return binder;
    }

    logger.LogDebug($"{nameof(IParameterBinder<object>)}<{{0}}> could not be resovled from DI container, using default JSON binder.", typeof(TModel).Name);

    return DefaultJsonParameterBinder.Instance;
}
```
![image](https://user-images.githubusercontent.com/249088/131198173-292d36cf-36a8-454c-83f4-433da9d86e78.png)

**Comment by maryamariyan** [comment]
looking

**Comment by Youssef1313** [comment]
I'm curious if the compiler version (not language version) you're using supports constant interpolated strings?

**Comment by DamianEdwards** [comment]
I'm using whatever compiler version is in latest internal VS2022 Preview 4.0 builds, so pretty much as new as it gets.

**Comment by Youssef1313** [comment]
Thanks for confirming @DamianEdwards 

@maryamariyan Small observations given a very quick look here:


https://github.com/dotnet/roslyn-analyzers/blob/7123df44e4503f5426290030d8187a3edb92bed7/src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/LoggerMessageDefineAnalyzer.cs#L250-L251

1. Why we're looking the Value if HasValue is false? I don't really get this part.
2. We should look at constant value for interpolation strings as well, not only literals. But this will work only on a compiler supporting constant interpolated strings. For older compiler versions, this will give false positives.

**Comment by jaredpar** [comment]
@DamianEdwards Can you give us two bits of info:

1. What does `#error version` print when you add it to the code?
2. Are you using `net6.0`? 

Presumably yes to (2) but want to check

**Comment by DamianEdwards** [comment]
@jaredpar 
`Error	CS8304	Compiler version: '4.0.0-4.21426.10 (6898d692)'. Language version: preview.`
Yes I'm using `net6.0`

**Comment by jaredpar** [comment]
That version should support const interpolated strings so that shoudn't be an issue here

**Comment by jmarolf** [comment]
@jaredpar I assume IOperation will not tell us about constant interpolated strings until @333fred checks in the api correct?

**Comment by 333fred** [comment]
There is no special API for constant interpolated strings. You just have an `IInterpolatedStringOperation` with a non-null `ConstantValue`.

**Comment by jmarolf** [comment]
@maryamariyan can you post what you are seeing? My understanding is that we are never getting a non-null `ConstantValue` in the case above

**Comment by maryamariyan** [comment]
we merged a fix for this on the release/6.0.1xx branch

**Comment by jmarolf** [comment]
closed with https://github.com/dotnet/roslyn-analyzers/pull/5480

**Comment by MarkLFT** [comment]
I am using VS2022 17.1.0 Preview 1.  And I am still getting this warning.  I am simply catching a thrown exception and trying to log it.

`catch (Exception error)
        {
            _logger.LogError(error, error.Message);
        }`

If I try the _logger.LogError(error);  I received a CS1503, and if I use the error.Message as a string, I receive a CA2254 warning.  I have never received this warning before, but now I have hundreds of warnings popping up because of this.
