### ISSUE TITLE
Analyzer 'Desktop.Analyzers.CSharpDoNotUseInsecureDTDProcessingAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#855]
1. Clean RoslynDev hive on your machine
2. Get latest sources of roslyn and build
3. Get latest sources of roslyn-analyzers and build
4. devenv /rootsuffix RoslynDev
5. Open Roslyn.sln

Got the following AD0001 in the error list:
```
Severity	Code	Description	Project	File	Line	Source	Tool	Detail Description
Error	AD0001	Analyzer 'Desktop.Analyzers.CSharpDoNotUseInsecureDTDProcessingAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.	Workspaces.Desktop		1	IntelliSense	Desktop.CSharp.Analyzers	Analyzer 'Desktop.Analyzers.CSharpDoNotUseInsecureDTDProcessingAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: Microsoft.CodeAnalysis.Workspaces.Desktop
SyntaxTree: C:\roslyn-internal\Open\src\Workspaces\Core\Desktop\Workspace\Host\TemporaryStorage\TemporaryStorageServiceFactory.MemoryMappedFiles.cs
SyntaxNode: _end = checked(_start + length) ... [AssignmentExpressionSyntax]@[11364..11395) (254,20)-(254,51)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Analyzer.Utilities.ITypeSymbolExtensions.DerivesFrom(ITypeSymbol symbol, INamedTypeSymbol candidateBaseType, Boolean baseTypesOnly)
   at Analyzer.Utilities.ISymbolExtensions.MatchMemberDerivedByName(ISymbol member, INamedTypeSymbol type, String name)
   at Analyzer.Utilities.ISymbolExtensions.MatchMethodDerivedByName(ISymbol member, INamedTypeSymbol type, String name)
   at Desktop.Analyzers.SecurityDiagnosticHelpers.IsXmlDocumentCtorDerived(IMethodSymbol method, CompilationSecurityTypes xmlTypes) in c:\roslyn-analyzers\src\Desktop.Analyzers\Core\Helpers\SecurityDiagnosticHelpers.cs:line 19
   at Desktop.Analyzers.DoNotUseInsecureDTDProcessingAnalyzer`1.Analyzer.AnalyzeNodeForXmlDocument(SyntaxNodeAnalysisContext context) in c:\roslyn-analyzers\src\Desktop.Analyzers\Core\DoNotUseInsecureDTDProcessing.cs:line 440
   at Desktop.Analyzers.DoNotUseInsecureDTDProcessingAnalyzer`1.Analyzer.AnalyzeNode(SyntaxNodeAnalysisContext context) in c:\roslyn-analyzers\src\Desktop.Analyzers\Core\DoNotUseInsecureDTDProcessing.cs:line 150
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass42_1`1.<ExecuteSyntaxNodeAction>b__1()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info)
-----
'.
```

**Comment by mavasani** [comment]
Seems like NRE in AnalyzerUtilties.

**Comment by bkoelman** [comment]
I'm also getting this. 8 times without a stack trace, then twice with a stacktrace that's different from @mavasani:

```
Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Warning	AD0001	Analyzer 'Desktop.Analyzers.DoNotUseInsecureDTDProcessingAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.	DogAgilityCompetition.Controller		1	Active	Analyzer 'Desktop.Analyzers.DoNotUseInsecureDTDProcessingAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: DogAgilityCompetitionController
IOperation: AssignmentExpression
SyntaxTree: E:\Bart\Source\Repos\DogAgilityCompetitionManagement\src\Controller\UI\Forms\LogForm.cs
SyntaxNode: TextBoxAppender.Mode = TextBoxAppenderMode ... [AssignmentExpressionSyntax]@[2479..2529) (74,12)-(74,62)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Desktop.Analyzers.DoNotUseInsecureDTDProcessingAnalyzer.Analyzer.AnalyzeAssignment(OperationAnalysisContext context)
   at Desktop.Analyzers.DoNotUseInsecureDTDProcessingAnalyzer.Analyzer.AnalyzeOperation(OperationAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass43_1.<ExecuteOperationAction>b__1()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info)
-----
'.
```

Source code referenced in exception:
https://github.com/bkoelman/DogAgilityCompetitionManagement/blob/master/src/Controller/UI/Forms/LogForm.cs#L75

**Comment by mavasani** [comment]
Fixed with https://github.com/dotnet/roslyn-analyzers/pull/981

**Comment by bkoelman** [comment]
I've run `cibuild` on latest sources, then installed `Prepelease\Desktop.Analyzers.1.2.0-beta2.nupkg` into my project. I am still getting errors with the same stacktrace:

```
Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Error	AD0001	Analyzer 'Desktop.Analyzers.DoNotUseInsecureDTDProcessingAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.	DogAgilityCompetition.Controller		1	Active	Analyzer 'Desktop.Analyzers.DoNotUseInsecureDTDProcessingAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: DogAgilityCompetitionController
IOperation: AssignmentExpression
SyntaxTree: E:\Bart\Source\Repos\DogAgilityCompetitionManagement\src\Controller\UI\Forms\LogForm.cs
SyntaxNode: TextBoxAppender.Mode = TextBoxAppenderMode ... [AssignmentExpressionSyntax]@[2479..2529) (74,12)-(74,62)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Desktop.Analyzers.DoNotUseInsecureDTDProcessingAnalyzer.OperationAnalyzer.AnalyzeAssignment(OperationAnalysisContext context)
   at Desktop.Analyzers.DoNotUseInsecureDTDProcessingAnalyzer.OperationAnalyzer.AnalyzeOperation(OperationAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass43_1.<ExecuteOperationAction>b__1()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info)
-----
'.
```

Looking at the fix, I do not see changes in the `AnalyzeAssignment` method. Can you please check again?

**Comment by mavasani** [comment]
That seems like a different issue from NRE in DerivesFrom. Can you file a separate issue?
